// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNn2pqbQdDT4iSdo8Iazc6U9jsnHTQ5pk',
    appId: '1:16606931698:web:7911defaef2f6817943e6b',
    messagingSenderId: '16606931698',
    projectId: 'unilever-b31a9',
    authDomain: 'unilever-b31a9.firebaseapp.com',
    storageBucket: 'unilever-b31a9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxO88G8qBqKQZ-LXQDwfkpUnrcQ3xt12g',
    appId: '1:16606931698:android:cb4ef46afcfaa35b943e6b',
    messagingSenderId: '16606931698',
    projectId: 'unilever-b31a9',
    storageBucket: 'unilever-b31a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-rc7CF0_8bj8ea-kQ3ysfESmQA6LAiws',
    appId: '1:16606931698:ios:25f1c50d9af789f8943e6b',
    messagingSenderId: '16606931698',
    projectId: 'unilever-b31a9',
    storageBucket: 'unilever-b31a9.appspot.com',
    iosBundleId: 'com.example.unileverApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-rc7CF0_8bj8ea-kQ3ysfESmQA6LAiws',
    appId: '1:16606931698:ios:e1fbda4092753e04943e6b',
    messagingSenderId: '16606931698',
    projectId: 'unilever-b31a9',
    storageBucket: 'unilever-b31a9.appspot.com',
    iosBundleId: 'com.example.unileverApp.RunnerTests',
  );
}
